import React from 'react'
import { FaBook } from "react-icons/fa";
import { GoDotFill } from "react-icons/go";
import { MdOutlineWorkOutline } from "react-icons/md";
import { GrTechnology } from "react-icons/gr";
import { IoIosDocument } from "react-icons/io";


const education = [
  {
    degree: 'Bachelor of Technology in Computer Science and Engineering',
    institution: 'Amity University, Uttar Pradesh',
    graduation: 'Expected Graduation: May 2025'
  },
  {
    degree: 'Higher Secondary Certificate (HSC)',
    institution: 'Whitehall Public School, Rampur',
    graduation: 'Graduated: March 2021'
  }
];

const workExp = [
  {
    title: 'Technology and Design Advisory Intern',
    company: 'Headsup Corporation',
    duration: 'May 2024 - July 2024',
    description: 'Worked on developing software solutions using MERN stack.'
  },
  {
    title: 'AI Code Evaluator',
    company: 'Remotasks',
    duration: 'September 2023 - Febraury 2024',
    description: 'Evaluated codes generated by different AI models.'
  }
];

const techStack = [
  { name: 'React', level: 75 },
  { name: 'Node.js', level: 70 },
  { name: 'MongoDB', level: 60 },
  { name: 'Docker', level: 40 },
  { name: 'Tailwind', level: 65 },
  { name: 'Git', level: 70 },
  { name: 'VS Code', level: 85 },
  { name: 'Express', level: 65 },
  { name: 'C++', level: 40 },
  { name: 'Python', level: 35 }
];

const Resume = () => {
  return (
    <div className='mx-4 mt-6'>
      <div className='bg-[#2a2a2a] p-8 rounded-lg shadow-gray-900 drop-shadow-lg hover:drop-shadow-2xl'>
        <div className='flex items-center gap-4 mb-8 text-xl'>
          <div className='text-[#49494e]'><FaBook /></div>
          <div className='font-semibold'>Education</div>
        </div>
        {education.map((edu, index) => (
          <div className='flex items-start text-xs gap-6 mb-4' key={index}>
            <div className='pt-[4px]'><GoDotFill /></div>
            <div>
              <h3 className='text-sm font-semibold'>{edu.degree}</h3>
              <p className='text-[#797982] text-sm'>{edu.institution}</p>
              <p className='text-[#49494e] text-sm'>{edu.graduation}</p>
            </div>
          </div>
        ))}
      </div>

      <div className='bg-[#2a2a2a] p-8 rounded-lg shadow-gray-900 drop-shadow-lg hover:drop-shadow-2xl mt-4'>
        <div className='flex items-center gap-4 mb-8 text-xl'>
          <div className='text-[#49494e]'><MdOutlineWorkOutline /></div>
          <div className='font-semibold'>Work Experience</div>
        </div>
        {workExp.map((exp, index) => (
          <div className='flex items-start text-xs gap-6 mb-4' key={index}>
            <div className='pt-[4px]'><GoDotFill /></div>
            <div>
              <h3 className='text-sm font-semibold'>{exp.title}</h3>
              <p className='text-[#797982] text-sm'>{exp.company}</p>
              <p className='text-[#49494e] text-sm'>{exp.duration}</p>
              <p className='text-[#49494e] text-sm'>{exp.description}</p>
            </div>
          </div>
        ))}
      </div>

      <div className='bg-[#2a2a2a] p-8 rounded-lg shadow-gray-900 drop-shadow-lg hover:drop-shadow-2xl my-4'>
        <div className='flex items-center gap-4 mb-8 text-xl'>
          <div className='text-[#49494e]'><GrTechnology /></div>
          <div className='font-semibold'>My Tech Stack</div>
        </div>
        <div>
          {techStack.map((tech, index) => (
            <div key={index} className='mb-4'>
              <div className='flex justify-between mb-1'>
                <span className='text-white'>{tech.name}</span>
                <span className='text-white'>{tech.level}%</span>
              </div>
              <div className='w-full bg-gray-600 rounded-full h-2'>
                <div
                  className='bg-[#FFCF75] h-2 rounded-full'
                  style={{ width: `${tech.level}%` }}
                ></div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className='flex justify-center items-center my-4'>
        <a href='https://firebasestorage.googleapis.com/v0/b/umarsalman-portfolio.appspot.com/o/resume%2FumrResume11.pdf?alt=media&token=2c390662-5764-47f3-9699-25e55c78b6d7' download='Resume'>
        <div className='flex cursor-pointer items-center gap-1 justify-center bg-[#2a2a2a] p-2 rounded-xl hover:bg-[#1e1d1d]'>
          <div><IoIosDocument/></div>
          <div>Download Resume</div>
        </div>
        </a>
      </div>

    </div>
  )
}

export default Resume
